"""
Static achievement definitions — 50 achievements across 5 categories.
Keys are achievement IDs used throughout the system.
"""

from typing import Dict

ACHIEVEMENTS: Dict[str, dict] = {

    # ── NUTRITION (10) ─────────────────────────────────────────────────────────

    "first_meal": {
        "id": "first_meal",
        "name": "First Bite",
        "description": "Log your first meal",
        "icon": "🍽️",
        "xp_reward": 50,
        "category": "nutrition",
        "condition_type": "count",
        "condition_value": 1,
        "condition_field": "food_logs_count",
    },
    "week_logger": {
        "id": "week_logger",
        "name": "Week Logger",
        "description": "Log every meal for 7 days straight",
        "icon": "📅",
        "xp_reward": 200,
        "category": "nutrition",
        "condition_type": "streak",
        "condition_value": 7,
        "condition_field": "nutrition_streak",
    },
    "macro_master": {
        "id": "macro_master",
        "name": "Macro Master",
        "description": "Hit all macro targets in one day",
        "icon": "🎯",
        "xp_reward": 150,
        "category": "nutrition",
        "condition_type": "special",
        "condition_value": 1,
        "condition_field": "macro_adherence",
    },
    "calorie_consistent": {
        "id": "calorie_consistent",
        "name": "Calorie Consistent",
        "description": "Stay within 100 calories of your goal for 5 days in a row",
        "icon": "📊",
        "xp_reward": 300,
        "category": "nutrition",
        "condition_type": "streak",
        "condition_value": 5,
        "condition_field": "calorie_adherence_streak",
    },
    "hydration_hero": {
        "id": "hydration_hero",
        "name": "Hydration Hero",
        "description": "Drink 2L of water in a single day",
        "icon": "💧",
        "xp_reward": 100,
        "category": "nutrition",
        "condition_type": "threshold",
        "condition_value": 2000,
        "condition_field": "daily_water_ml",
    },
    "meal_planner": {
        "id": "meal_planner",
        "name": "Meal Planner",
        "description": "Use the AI meal plan feature 5 times",
        "icon": "🗓️",
        "xp_reward": 100,
        "category": "nutrition",
        "condition_type": "count",
        "condition_value": 5,
        "condition_field": "meal_plan_count",
    },
    "photo_foodie": {
        "id": "photo_foodie",
        "name": "Photo Foodie",
        "description": "Log 10 meals using a food photo",
        "icon": "📸",
        "xp_reward": 150,
        "category": "nutrition",
        "condition_type": "count",
        "condition_value": 10,
        "condition_field": "photo_logs_count",
    },
    "nutrition_month": {
        "id": "nutrition_month",
        "name": "Nutrition Month",
        "description": "Log nutrition for 30 consecutive days",
        "icon": "🏆",
        "xp_reward": 500,
        "category": "nutrition",
        "condition_type": "streak",
        "condition_value": 30,
        "condition_field": "nutrition_streak",
    },
    "protein_king": {
        "id": "protein_king",
        "name": "Protein King",
        "description": "Hit your protein goal 7 days in a row",
        "icon": "💪",
        "xp_reward": 250,
        "category": "nutrition",
        "condition_type": "streak",
        "condition_value": 7,
        "condition_field": "nutrition_streak",
    },
    "clean_eater": {
        "id": "clean_eater",
        "name": "Clean Eater",
        "description": "Log a total of 50 meals",
        "icon": "🥗",
        "xp_reward": 200,
        "category": "nutrition",
        "condition_type": "count",
        "condition_value": 50,
        "condition_field": "food_logs_count",
    },

    # ── WORKOUT (15) ───────────────────────────────────────────────────────────

    "first_sweat": {
        "id": "first_sweat",
        "name": "First Sweat",
        "description": "Complete your first workout session",
        "icon": "🏋️",
        "xp_reward": 100,
        "category": "workout",
        "condition_type": "count",
        "condition_value": 1,
        "condition_field": "workout_sessions_count",
    },
    "ten_sessions": {
        "id": "ten_sessions",
        "name": "Ten Sessions",
        "description": "Complete 10 workout sessions",
        "icon": "🔟",
        "xp_reward": 300,
        "category": "workout",
        "condition_type": "count",
        "condition_value": 10,
        "condition_field": "workout_sessions_count",
    },
    "fifty_sessions": {
        "id": "fifty_sessions",
        "name": "Fifty Sessions",
        "description": "Complete 50 workout sessions",
        "icon": "🥇",
        "xp_reward": 1000,
        "category": "workout",
        "condition_type": "count",
        "condition_value": 50,
        "condition_field": "workout_sessions_count",
    },
    "iron_week": {
        "id": "iron_week",
        "name": "Iron Week",
        "description": "Work out 5 times in one week",
        "icon": "⚡",
        "xp_reward": 400,
        "category": "workout",
        "condition_type": "count",
        "condition_value": 5,
        "condition_field": "weekly_sessions",
    },
    "early_bird": {
        "id": "early_bird",
        "name": "Early Bird",
        "description": "Complete a workout before 8 AM",
        "icon": "🌅",
        "xp_reward": 150,
        "category": "workout",
        "condition_type": "special",
        "condition_value": 8,
        "condition_field": "workout_start_hour",
    },
    "night_owl": {
        "id": "night_owl",
        "name": "Night Owl",
        "description": "Complete a workout after 9 PM",
        "icon": "🦉",
        "xp_reward": 150,
        "category": "workout",
        "condition_type": "special",
        "condition_value": 21,
        "condition_field": "workout_start_hour",
    },
    "century_calories": {
        "id": "century_calories",
        "name": "Calorie Crusher",
        "description": "Burn 500 calories in a single workout",
        "icon": "🔥",
        "xp_reward": 200,
        "category": "workout",
        "condition_type": "threshold",
        "condition_value": 500,
        "condition_field": "session_calories",
    },
    "marathon_man": {
        "id": "marathon_man",
        "name": "Marathon Man",
        "description": "Run/jog a total of 42 km across all sessions",
        "icon": "🏃",
        "xp_reward": 1000,
        "category": "workout",
        "condition_type": "threshold",
        "condition_value": 42,
        "condition_field": "total_jog_distance_km",
    },
    "heavy_lifter": {
        "id": "heavy_lifter",
        "name": "Heavy Lifter",
        "description": "Log a total of 10,000 kg lifted",
        "icon": "🏗️",
        "xp_reward": 500,
        "category": "workout",
        "condition_type": "threshold",
        "condition_value": 10000,
        "condition_field": "total_volume_kg",
    },
    "workout_streak_7": {
        "id": "workout_streak_7",
        "name": "Week Warrior",
        "description": "Work out 7 days in a row",
        "icon": "🌟",
        "xp_reward": 500,
        "category": "workout",
        "condition_type": "streak",
        "condition_value": 7,
        "condition_field": "workout_streak",
    },
    "workout_streak_30": {
        "id": "workout_streak_30",
        "name": "Iron Discipline",
        "description": "Work out 30 days in a row",
        "icon": "💎",
        "xp_reward": 2000,
        "category": "workout",
        "condition_type": "streak",
        "condition_value": 30,
        "condition_field": "workout_streak",
    },
    "full_body": {
        "id": "full_body",
        "name": "Full Body Week",
        "description": "Train every major muscle group in one week",
        "icon": "🧬",
        "xp_reward": 300,
        "category": "workout",
        "condition_type": "special",
        "condition_value": 9,
        "condition_field": "muscle_groups_week",
    },
    "chest_day": {
        "id": "chest_day",
        "name": "Chest Day",
        "description": "Log 10 chest workouts",
        "icon": "💥",
        "xp_reward": 200,
        "category": "workout",
        "condition_type": "count",
        "condition_value": 10,
        "condition_field": "chest_sessions",
    },
    "leg_day_hero": {
        "id": "leg_day_hero",
        "name": "Leg Day Hero",
        "description": "Log 10 leg workouts",
        "icon": "🦵",
        "xp_reward": 200,
        "category": "workout",
        "condition_type": "count",
        "condition_value": 10,
        "condition_field": "leg_sessions",
    },
    "recovery_pro": {
        "id": "recovery_pro",
        "name": "Recovery Pro",
        "description": "Log 3 rest days with active recovery",
        "icon": "🧘",
        "xp_reward": 150,
        "category": "workout",
        "condition_type": "count",
        "condition_value": 3,
        "condition_field": "rest_sessions",
    },

    # ── GAME (10) ──────────────────────────────────────────────────────────────

    "first_territory": {
        "id": "first_territory",
        "name": "Land Grabber",
        "description": "Claim your first territory",
        "icon": "🗺️",
        "xp_reward": 200,
        "category": "game",
        "condition_type": "count",
        "condition_value": 1,
        "condition_field": "territories_count",
    },
    "five_territories": {
        "id": "five_territories",
        "name": "Expanding Empire",
        "description": "Claim 5 territories",
        "icon": "🏴",
        "xp_reward": 400,
        "category": "game",
        "condition_type": "count",
        "condition_value": 5,
        "condition_field": "territories_count",
    },
    "twenty_territories": {
        "id": "twenty_territories",
        "name": "Territory King",
        "description": "Claim 20 territories",
        "icon": "👑",
        "xp_reward": 1000,
        "category": "game",
        "condition_type": "count",
        "condition_value": 20,
        "condition_field": "territories_count",
    },
    "big_land": {
        "id": "big_land",
        "name": "Big Land",
        "description": "Claim a single territory over 1 km²",
        "icon": "🌍",
        "xp_reward": 500,
        "category": "game",
        "condition_type": "threshold",
        "condition_value": 1.0,
        "condition_field": "territory_area_km2",
    },
    "explorer": {
        "id": "explorer",
        "name": "Explorer",
        "description": "Jog in 3 different neighbourhoods",
        "icon": "🧭",
        "xp_reward": 300,
        "category": "game",
        "condition_type": "count",
        "condition_value": 3,
        "condition_field": "distinct_jog_zones",
    },
    "landlord": {
        "id": "landlord",
        "name": "Landlord",
        "description": "Own 10 km² of total territory",
        "icon": "🏙️",
        "xp_reward": 1000,
        "category": "game",
        "condition_type": "threshold",
        "condition_value": 10.0,
        "condition_field": "total_territory_km2",
    },
    "speed_demon": {
        "id": "speed_demon",
        "name": "Speed Demon",
        "description": "Complete a 5 km jog in under 25 minutes",
        "icon": "⚡",
        "xp_reward": 500,
        "category": "game",
        "condition_type": "special",
        "condition_value": 25,
        "condition_field": "jog_pace",
    },
    "first_encounter": {
        "id": "first_encounter",
        "name": "First Encounter",
        "description": "Enter someone else's territory",
        "icon": "🚩",
        "xp_reward": 150,
        "category": "game",
        "condition_type": "special",
        "condition_value": 1,
        "condition_field": "enemy_territory_visit",
    },
    "jog_streak": {
        "id": "jog_streak",
        "name": "Jog Streak",
        "description": "Jog 5 days in a row",
        "icon": "🏅",
        "xp_reward": 400,
        "category": "game",
        "condition_type": "streak",
        "condition_value": 5,
        "condition_field": "jog_streak",
    },
    "marathon_territory": {
        "id": "marathon_territory",
        "name": "Marathon Territory",
        "description": "Claim territory from a 10 km jog",
        "icon": "🗾",
        "xp_reward": 750,
        "category": "game",
        "condition_type": "threshold",
        "condition_value": 10.0,
        "condition_field": "jog_distance_km",
    },

    # ── CONSISTENCY (10) ───────────────────────────────────────────────────────

    "streak_3": {
        "id": "streak_3",
        "name": "Habit Forming",
        "description": "Open the app 3 days in a row",
        "icon": "📱",
        "xp_reward": 50,
        "category": "consistency",
        "condition_type": "streak",
        "condition_value": 3,
        "condition_field": "app_streak",
    },
    "streak_7": {
        "id": "streak_7",
        "name": "Weekly Regular",
        "description": "Open the app 7 days in a row",
        "icon": "🗓️",
        "xp_reward": 150,
        "category": "consistency",
        "condition_type": "streak",
        "condition_value": 7,
        "condition_field": "app_streak",
    },
    "streak_30": {
        "id": "streak_30",
        "name": "Monthly Dedication",
        "description": "Open the app 30 days in a row",
        "icon": "🌙",
        "xp_reward": 500,
        "category": "consistency",
        "condition_type": "streak",
        "condition_value": 30,
        "condition_field": "app_streak",
    },
    "streak_100": {
        "id": "streak_100",
        "name": "Centurion",
        "description": "Open the app 100 days in a row",
        "icon": "💯",
        "xp_reward": 2000,
        "category": "consistency",
        "condition_type": "streak",
        "condition_value": 100,
        "condition_field": "app_streak",
    },
    "goal_setter": {
        "id": "goal_setter",
        "name": "Goal Setter",
        "description": "Complete onboarding and set your fitness goal",
        "icon": "🎯",
        "xp_reward": 100,
        "category": "consistency",
        "condition_type": "special",
        "condition_value": 1,
        "condition_field": "has_goal",
    },
    "profile_complete": {
        "id": "profile_complete",
        "name": "Profile Complete",
        "description": "Fill in all profile fields",
        "icon": "✅",
        "xp_reward": 50,
        "category": "consistency",
        "condition_type": "special",
        "condition_value": 1,
        "condition_field": "all_fields_filled",
    },
    "week_complete": {
        "id": "week_complete",
        "name": "Perfect Week",
        "description": "Complete all goals for an entire week",
        "icon": "🌈",
        "xp_reward": 750,
        "category": "consistency",
        "condition_type": "special",
        "condition_value": 7,
        "condition_field": "week_all_goals",
    },
    "monthly_warrior": {
        "id": "monthly_warrior",
        "name": "Monthly Warrior",
        "description": "Complete all goals for an entire month",
        "icon": "🏆",
        "xp_reward": 3000,
        "category": "consistency",
        "condition_type": "special",
        "condition_value": 30,
        "condition_field": "month_all_goals",
    },
    "comeback_kid": {
        "id": "comeback_kid",
        "name": "Comeback Kid",
        "description": "Return to the app after being away for 7+ days",
        "icon": "🔄",
        "xp_reward": 100,
        "category": "consistency",
        "condition_type": "special",
        "condition_value": 7,
        "condition_field": "days_away",
    },
    "perfectionist": {
        "id": "perfectionist",
        "name": "Perfectionist",
        "description": "Hit 100% macro adherence for 3 days in a row",
        "icon": "💫",
        "xp_reward": 400,
        "category": "consistency",
        "condition_type": "streak",
        "condition_value": 3,
        "condition_field": "macro_perfect_streak",
    },

    # ── SOCIAL (5) ─────────────────────────────────────────────────────────────

    "leaderboard_entry": {
        "id": "leaderboard_entry",
        "name": "On the Board",
        "description": "Appear on the global leaderboard",
        "icon": "📋",
        "xp_reward": 100,
        "category": "social",
        "condition_type": "special",
        "condition_value": 1,
        "condition_field": "leaderboard_position",
    },
    "top_100": {
        "id": "top_100",
        "name": "Top 100",
        "description": "Reach the top 100 on the global leaderboard",
        "icon": "💯",
        "xp_reward": 300,
        "category": "social",
        "condition_type": "threshold",
        "condition_value": 100,
        "condition_field": "leaderboard_rank",
    },
    "top_10": {
        "id": "top_10",
        "name": "Top 10",
        "description": "Reach the top 10 on the global leaderboard",
        "icon": "🌠",
        "xp_reward": 1000,
        "category": "social",
        "condition_type": "threshold",
        "condition_value": 10,
        "condition_field": "leaderboard_rank",
    },
    "territory_champ": {
        "id": "territory_champ",
        "name": "Territory Champion",
        "description": "Hold the #1 spot on the territory leaderboard",
        "icon": "🥇",
        "xp_reward": 1500,
        "category": "social",
        "condition_type": "special",
        "condition_value": 1,
        "condition_field": "territory_rank",
    },
    "ai_chat_10": {
        "id": "ai_chat_10",
        "name": "AI Addict",
        "description": "Have 10 AI chat conversations",
        "icon": "🤖",
        "xp_reward": 150,
        "category": "social",
        "condition_type": "count",
        "condition_value": 10,
        "condition_field": "ai_chat_count",
    },
}
